name: Nodes

on: 
  workflow_dispatch:
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: '0 */12 * * *'

jobs: 

  my-job: 
    name: Max Job
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3     #git clone
    - uses: actions/setup-node@v3   #Node.js环境
      with:
        node-version: '16.x'        #Node.js 16.x
    - uses: actions/setup-python@v4 #python环境
      with:
        python-version: '3.x'       #python 3.x
        cache: 'pip'                #pip cache
    - name: Timezone #UTC+0 → UTC+8
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: npm
      run: | #安装npm包
         cd ./utils/rm/
         npm ci
    - name: pip
      run: | #安装pip包
         pip install -r ./utils/clashcheck/requirements.txt
    - name: clashcheck #because ./utils/clashcheck/config.yaml so input ./utils/clashcheck/input.yaml
      run: cd ./utils/clashcheck/ && python main.py && rm input.yaml #output ./utils/clashcheck/check.yaml & delete ./utils/clashcheck/input.yaml
    - name: move clashcheck to clash2base64 #input ./utils/clashcheck/check.yaml
      run: mv ./utils/clashcheck/check.yaml ./utils/subconverter/check.yaml #output ./utils/subconverter/check.yaml
    - name: clash2base64 #input ./utils/subconverter/check.yaml
      run: ./utils/subconverter/subconverter -g --artifact "clash2base64" && rm utils/subconverter/check.yaml #output ./utils/subconverter/check & delete ./utils/subconverter/check.yaml
    - name: base64 decode #because ./utils/subconverter/generate.ini so input ./utils/subconverter/check
      run: base64 -d ./utils/subconverter/check > ./utils/rm/url && rm ./utils/subconverter/check   #output ./utils/rm/url & delete ./utils/subconverter/check ./utils/rm/url1
    - name: remove & rename #input ./utils/rm/url
      run: cd ./utils/rm/ && npm start #output ./utils/rm/out
    - name: url & https
      run: | #input ./utils/rm/out
         rm ./utils/rm/url             #delete ./utils/rm/url
         mv ./utils/rm/out ./url       #output ./url
         base64 ./url > ./utils/subconverter/base64 -w 0 #url文件base64编码引入subconverter
         sort url -o url #将url排序并修改至原文件，突出增删的节点 output ./url
    - name: long & Clash.yaml
      run: | #input ./utils/subconverter/base64
         ./utils/subconverter/subconverter -g --artifact "clash"
         ./utils/subconverter/subconverter -g --artifact "long"
         #output ./utils/subconverter/Clash.yaml ./utils/subconverter/long
         mv ./utils/subconverter/Clash.yaml ./Clash.yaml || true #output ./Clash.yaml
         mv ./utils/subconverter/long ./long || true #output ./Clash.yaml
         rm ./utils/subconverter/base64 #delete ./utils/subconverter/base64
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add .
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')更新"
        git push origin master
