name: speedtest

# 触发条件
on:
  workflow_dispatch:

  push:
    paths:
      - './Clash.yaml'
  schedule:
    - cron: '05 */12 * * *'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: speedtest
      run: |
        sudo sh ./utils/speedtest/speedtest.sh
        python ./utils/speedtest/output.py
        python ./utils/eternity_convert.py
        sudo sh ./utils/url.sh
        cp base64 ./utils/subconverter/ || true
        ./utils/subconverter/subconverter -g --artifact "provider"
        mv ./utils/subconverter/provider.yaml ./provider.yaml || true
    - name: commit
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add base64
        git add Eternity
        git add Eternity.yml
        git add provider.yaml
        git add README.md
        git add ./update/*
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')筛选节点"
        git push origin master
